name: tsql_linter
on: [push]

jobs:
  build:
    name: Lint Code
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3.0.2

      - name: TSQLLint
        uses: lowlydba/tsqllint-action@v1.0.0
        with:
          path: "*.sql *.tsql"
          config: "./.tsqllintrc"
          comment: true